var levels = [

// Level 1 (0)
["WWWWWWW..WWWWWWW",
 "WWWWWWWXXWWWWWWW",
 "WWWW........WWWW",
 "WWWW........WWWW",
 "WWWW.....x..WWWW",
 "WWWW........WWWW",
 "WWWW........WWWW",
 "WWWW........WWWW",
 "WWWW........WWWW",
 "WWWW........WWWW",
 "WWWW........WWWW",
 "WWWW..b.....WWWW",
 "WWWW........WWWW",
 "WWWW........WWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW"],
 
 // Level 2 (1)
["WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WW.......x...WWW",
 "WWHHHHHHHHHHHWWW",
 "WW.......n...XY.",
 "WW...........XY.",
 "WW........y..WWW",
 "WW...........WWW",
 "WW........WWWWWW",
 "WW..b.....WWWWWW",
 "WW........WWWWWW",
 "WW........WWWWWW",
 "WWWWWWW..WWWWWWW"],
 
 // Level 3 (1)
["WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWW..x.......WWW",
 "WWWHHHHHHHHHHWWW",
 "WWW..........WWW",
 "WWW.......n..WWW",
 "WWW..........WWW",
 ".............XY.",
 ".............XY.",
 "WWW.......y..WWW",
 "WWW..b.......WWW",
 "WWW..........WWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW"],
 
// Level 4 (1)
["WWWWWWWWWWWWWWWW",
 "WWWWWWWW.x.WWWWW",
 "WWWWWWWW.H.WWWWW",
 "WWWWWWWW.H.WWWWW",
 "WWWWWWWW.n.WWWWW",
 "WWWWWWWWWWWWWWWW",
 "W............WWW",
 ".............XY.",
 ".............XY.",
 "W............WWW",
 "W..b......y..WWW",
 "W............WWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW"],

// Level 5 (2)
["WWWWWWWWWWWWWWWW",
 "WWW.x.WWWWWWWWWW",
 "WWW.H.WWWWWWWWWW",
 "WWW.n.WWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "W....b....z.WWWW",
 "W...........WWWW",
 "............XYZ.",
 "............XYZ.",
 "W...........WWWW",
 "W...........WWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWW.y.WWWWW",
 "WWWWWWWW.H.WWWWW",
 "WWWWWWWW.s.WWWWW",
 "WWWWWWWWWWWWWWWW"],
 
 // Level 6 (1)
["WWWWWWWWWWWWWWWW",
 "WWWW.s.WWWWWWWWW",
 "WWWW.H.WWWWWWWWW",
 "WWWW.x.WWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "W.........WWWWWW",
 "W......z..WWWWWW",
 "..........W....W",
 "..........WyHHsW",
 "W.........W....W",
 "W..b......WWWWWW",
 "W.........WWWWWW",
 "WWWWWWWXXWWWWWWW",
 "WWWWWWWYYWWWWWWW",
 "WWWWWWWZZWWWWWWW",
 "WWWWWWW..WWWWWWW"],
 
 // Level 7 (1)
["WWWWWWW..WWWWWWW",
 "W..............W",
 "W.....y........W",
 "W..............W",
 "W..............W",
 "WWW............W",
 "WWW............W",
 ".YX............W",
 ".YX............W",
 "WWW...x........W",
 "W..........b...W",
 "WWWW....WWHHHWWW",
 "WWWW....WW...WWW",
 "WWWWWWWWWW...WWW",
 "WWWWWWWWWW.s.WWW",
 "WWWWWWWWWWWWWWWW"],
 
  // Level 8 (1)
["WWWWWWWWWWWWWWWW",
 "W..............W",
 "W.....y........W",
 "W..............W",
 "W..............W",
 "W..............W",
 "WWW............W",
 ".YX.............",
 ".YX.............",
 "WWW...x........W",
 "W.........n....W",
 "WWWW....WWHHHWWW",
 "WWWW....WW...WWW",
 "WWWWWWWWWW...WWW",
 "WWWWWWWWWW..sWWW",
 "WWWWWWWWWWWWWWWW"],
 
 // Level 9 (4)
["WWWWWWWWWWWWWWWW",
 "W..............W",
 "W..............W",
 "W..............W",
 "W...WWWWWWWW...W",
 "W...WsWWyW.W...W",
 "W...W.WW.W.W...W",
 "W...W.WW.W.W....",
 "W...W.WW.WnW....",
 "W...W.WW.W.W...W",
 "W...W.X..WxW...W",
 "W...WWWWWWWW...W",
 "W..............W",
 "W..............W",
 "W.....WYYW.....W",
 "WWWWWWW..WWWWWWW"],
 
  // Level 10 (2)
["WWWWWWW..WWWWWWW",
 "WWWWWWW..WWWWWWW",
 "WWWWWWW..WWWWWWW",
 "WWWW........WWWW",
 "WWWW...H..n.WWWW",
 "WWWWHH...HHHWWWW",
 "WWWWxnH.H.HyWWWW",
 "WWWWHH.....HWWWW",
 "WWWW...W....WWWW",
 "WWWW..HzH...WWWW",
 "WWWW...H.b..WWWW",
 "WWWW......s.WWWW",
 "WWWWWWWXXWWWWWWW",
 "WWWWWWWYYWWWWWWW",
 "WWWWWWWZZWWWWWWW",
 "WWWWWWW..WWWWWWW"],
 
   // Level 11 (2)
["WWWWWWW..WWWWWWW",
 "WWWWWWW..WWWWWWW",
 "WWWWWWW........W",
 "WWWWWWWWWWWWWW.W",
 "WWWWWWWWWWWWWW.W",
 "WWWW....W.sxWW.W",
 "WWWWWWWXW...WW.W",
 "..WWyH.........W",
 "..WWHH...b..WWWW",
 "W.WW........WWWW",
 "W.WWWWWYWWWWWWWW",
 "W.WWWWW.WWWWWWWW",
 "W.......WWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW"],
 
 // Level 12 (2)
["WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWW......W",
 "WWWWWWWWW.WWWW.W",
 "WWW..H.....X.W.W",
 "..W.WyH....W.W..",
 "..W..H.....b.W..",
 "W.W....s..xWWWWW",
 "W.WYWWWWWWWWWWWW",
 "W...WWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW"],
 
 // Level 13 (3) 
["WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWWWWWWWWWWWW",
 "WWWWWW.....WWWWW",
 "WWWW...W.W...WWW",
 "WWWW.H.....H.WWW",
 "WWWW...H.H..WWWW",
 "WWWW.bxWXW..WW..",
 "WWWW...WYWybWW..",
 "WWWW.H.......W.W",
 "WWWW.nH..H...W.W",
 "WWWWZWWWHW.....W",
 "WWWW.WWWzWWWWWWW",
 "WWWW.WWWWWWWWWWW",
 "WWWW.....WWWWWWW",
 "WWWWWWW..WWWWWWW"],
 
 // Level 14 (4)
["WWWWWWW..WWWWWWW",
 "W..............W",
 "WWWWWWWWWWWW...W",
 "W.X........W...W",
 "W......W.W.W...W",
 "W....W.W.WHW...W",
 "W....W.W.W....WW",
 "W......b.WnW..Z.",
 "W..XHX...WxW..Z.",
 "W.YYYYYWWWWW..WW",
 "W...H...X......W",
 "W.H...HWWWWWWW.W",
 "WXzH.....Wy..W.W",
 "W.H..XYb.W.WWW.W",
 "W........WsW...W",
 "WWWWWWWWWWWWWWWW"],


 ]


 var levelInfo = [
 	{advance: "up", charges: 0},
 	{advance: "right", charges: 1},
 	{advance: "right", charges: 1},
 	{advance: "right", charges: 1},
 	{advance: "right", charges: 2},
 	{advance: "down", charges: 1},
 	{advance: "left", charges: 1},
 	{advance: "left", charges: 1},
 	{advance: "down", charges: 4},
 	{advance: "down", charges: 2},
 	{advance: "left", charges: 2},
 	{advance: "left", charges: 2},
 	{advance: "down", charges: 3},
 	{advance: "right", charges: 4}
 ]